# Generated by Django 5.2.9 on 2026-03-20 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_historicalproject_institution_project_institution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalprojectuser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project user",
                "verbose_name_plural": "historical Project Users",
            },
        ),
        migrations.AlterModelOptions(
            name="projectuser",
            options={"verbose_name_plural": "Project Users"},
        ),
    ]
