# Generated by Django 4.2 on 2025-11-28 22:07

# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_historicalproject_institution_project_institution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalprojectuser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project user",
                "verbose_name_plural": "historical Project Users",
            },
        ),
        migrations.AlterModelOptions(
            name="projectuser",
            options={"verbose_name_plural": "Project Users"},
        ),
    ]
