# Generated by Django 4.2 on 2025-11-28 22:07

# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("allocation", "0006_alter_historicalallocation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allocationuser",
            options={"verbose_name_plural": "Allocation Users"},
        ),
        migrations.AlterModelOptions(
            name="historicalallocationuser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical allocation user",
                "verbose_name_plural": "historical Allocation Users",
            },
        ),
    ]
