# Generated by Django 5.2.9 on 2026-03-20 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("allocation", "0006_alter_historicalallocation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allocationuser",
            options={"verbose_name_plural": "Allocation Users"},
        ),
        migrations.AlterModelOptions(
            name="historicalallocationuser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical allocation user",
                "verbose_name_plural": "historical Allocation Users",
            },
        ),
    ]
